apiVersion: v1          # versión de la api
kind: Secret            # recurso secreto
metadata:
  name: mysql-pass      # nombre del secret
type: Opaque            # tipo genérico
stringData:
  password: "David12#$" # contraseña
  username: "david"     # usuario

