---
    - lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "^//.*}-updates\";$"
        line: "        \"origin=Debian,codename=${distro_codename}-updates\";"

    - lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "^//.*}-proposed-updates\";$"
        line: "        \"origin=Debian,codename=${distro_codename}-proposed-updates\";"
