---
    - ansible.builtin.iptables:
        chain: INPUT
        ctstate: [RELATED, ESTABLISHED]
        jump: ACCEPT

    - ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        jump: ACCEPT

    - ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        ctstate: NEW
        jump: ACCEPT

    - ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        ctstate: NEW
        jump: ACCEPT

    - ansible.builtin.iptables:
        chain: INPUT
        policy: DROP
