---
- name: Playbook principal
  hosts: all
  remote_user: debian
  become: true
  tasks:
    - import_tasks: install-nginx.yml
    - import_tasks: firewall.yml
    - import_tasks: config-sshd.yml
    - import_tasks: config-ua.yml
