---
- name: Instalar unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configurar actualizaciones automáticas
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644

- name: Habilitar actualizaciones de seguridad
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^Unattended-Upgrade::Allowed-Origins\s*{'
    line: 'Unattended-Upgrade::Allowed-Origins { "origin=Debian,codename=${distro_codename}-security"; };'
    backrefs: yes

- name: Reiniciar el servicio
  systemd:
    name: unattended-upgrades
    enabled: yes
    daemon_reload: yes
