---
      - name: Allow related and established connections
        ansible.builtin.iptables:
          chain: INPUT
          ctstate: ESTABLISHED,RELATED
          jump: ACCEPT

      - name: Allow loopback interface connections
        ansible.builtin.iptables:
          chain: INPUT
          in_interface: lo
          jump: ACCEPT

      - name: Allow ssh and http(s) connections
        ansible.builtin.iptables:
          chain: INPUT
          protocol: tcp
          destination_ports:
            - "22"
            - "80"
            - "443"
          jump: ACCEPT

      - name: DROP others
        ansible.builtin.iptables:
          chain: INPUT
          jump: DROP
...
