---
    - name: Install nginx 
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: HTML template
      ansible.builtin.template:
        src: templates/index-template.j2
        dest: /var/www/html/index.html
    
    - name: Start and enable service nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
...
