---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present

- name: Copiar configuración de Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify: restart nginx

- name: Crear directorio del sitio web
  file:
    path: /var/www/html
    state: directory
    mode: 0755

- name: Generar index.html personalizado
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Reiniciar Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
